resources:
- name: src
  type: git
  source:
    uri: https://github.com/ipfs/go-ipfs
    branch: master
- name: concourse
  type: git
  source:
    uri: https://github.com/victorbjelkholm/concourse
    branch: master

jobs:
- name: go-ipfs
  public: true
  plan:
  - get: src
  - get: concourse
  - task: install-and-test
    file: concourse/tasks/go-ipfs-install-and-test.yml

