resources:
- name: go-multiaddr-src
  type: git
  source:
    uri: https://github.com/victorbjelkholm/go-multiaddr
    branch: master

jobs:
- name: go-multiaddr
  public: true
  plan:
  - get: go-multiaddr-src
    trigger: true
  - task: test-linux
    config:
      platform: linux
      inputs:
        - name: go-multiaddr-src
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: 1.7.3
      run:
        path: make
        args: ["test"]
        dir: go-multiaddr-src
