resources:
- name: js-ipfs-api-src
  type: git
  source:
    uri: https://github.com/ipfs/js-ipfs-api
    branch: master
- name: concourse
  type: git
  source:
    uri: https://github.com/victorbjelkholm/concourse
    branch: master

jobs:
- name: js-ipfs-api
  public: true
  plan:
  - get: js-ipfs-api-src
  - get: concourse
  - task: install-and-test
    file: concourse/tasks/js-install-and-test.yml
