resources:
- name: js-multiaddr-src
  type: git
  source:
    uri: https://github.com/victorbjelkholm/js-multiaddr
    branch: master

jobs:
- name: js-multiaddr
  plan:
  - get: js-multiaddr-src
    trigger: true
  - task: install-and-test
    config:
      platform: linux
      inputs:
        - name: js-multiaddr-src
      image_resource:
        type: docker-image
        source: 
          repository: victorbjelkholm/alpine-node-git
          tag: latest
      params:
        CHROME_BIN: /usr/bin/chromium-browser 
      run:
        path: make
        args: ["test"]
        dir: js-multiaddr-src
