---
platform: linux

inputs:
  - name: {{src-path}}
    path: src/github.com/ipfs/go-ipfs

image_resource:
  type: docker-image
  source: 
    repository: golang
    tag: 1.7.3

run:
  path: sh
  args:
    - -exec
    - |
      export GOPATH=$(pwd)
      cd $GOPATH/src/github.com/ipfs/go-ipfs
      make deps
      TEST_NO_FUSE=1 go test ./...

params:
  src-path: src
