---
platform: linux

inputs:
  - name: js-ipfs-api-src

image_resource:
  type: docker-image
  source: 
    repository: node
    tag: "6"

run:
  path: sh
  dir: js-ipfs-api-src
  args:
    - -exec
    - |
      npm install npm@4.0.2
      npm version
      npm install
      npm run test:node
